# Production environment overrides

global:
  edition: "community"  # Change to "pro" if using Airbyte Enterprise

webapp:
  replicaCount: 2  # High availability
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Pod disruption budget
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

server:
  replicaCount: 2  # High availability
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

worker:
  replicaCount: 3  # Multiple workers for production
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 4Gi
  
  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

postgresql:
  primary:
    persistence:
      size: 100Gi
      storageClass: "fast-ssd"  # Use high-performance storage
    
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
  
  # Enable backups
  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: 30

minio:
  persistence:
    size: 200Gi
    storageClass: "standard"
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Enable ingress for production
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: airbyte.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: airbyte-prod-tls
      hosts:
        - airbyte.example.com

# Enable metrics and monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

# Affinity rules for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - airbyte
          topologyKey: kubernetes.io/hostname

