# Base Helm values for Airbyte
# These values are shared across all environments and can be overridden per environment

global:
  edition: "community"  # or "pro"
  
webapp:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

server:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    existingSecret: "airbyte-postgresql-secret"
    secretKeys:
      adminPasswordKey: "postgresql-password"
  
  primary:
    persistence:
      enabled: true
      size: 10Gi
    
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

# Temporal configuration
temporal:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Minio (for logs/state storage)
minio:
  enabled: true
  mode: standalone
  auth:
    existingSecret: "airbyte-minio-secret"
  
  persistence:
    enabled: true
    size: 20Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Ingress configuration (disabled by default, enable per environment)
ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: airbyte.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: airbyte-tls
      hosts:
        - airbyte.example.com

# Metrics and monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Enable in environments with Prometheus Operator

