# Staging environment overrides

global:
  edition: "community"

webapp:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

server:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  replicaCount: 2  # Multiple workers for staging
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

postgresql:
  primary:
    persistence:
      size: 20Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

minio:
  persistence:
    size: 50Gi

# Enable ingress for staging
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: airbyte-staging.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: airbyte-staging-tls
      hosts:
        - airbyte-staging.example.com

# Enable metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

