# SOPS configuration for secrets encryption
# Requires: sops and cloud KMS (AWS KMS, GCP KMS, or Azure Key Vault)

creation_rules:
  # Development secrets
  - path_regex: secrets/dev/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    # Replace with your actual KMS key ARN/ID
    kms: arn:aws:kms:us-east-1:123456789012:key/dev-key-id
    # Or use GCP KMS
    # gcp_kms: projects/my-project/locations/global/keyRings/airbyte/cryptoKeys/dev
  
  # Staging secrets
  - path_regex: secrets/staging/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    kms: arn:aws:kms:us-east-1:123456789012:key/staging-key-id
  
  # Production secrets
  - path_regex: secrets/prod/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    kms: arn:aws:kms:us-east-1:123456789012:key/prod-key-id

# Example usage:
# Encrypt: sops -e secrets/dev/secrets.yaml > secrets/dev/secrets.enc.yaml
# Decrypt: sops -d secrets/dev/secrets.enc.yaml
# Edit: sops secrets/dev/secrets.enc.yaml

