# Development environment overrides

global:
  edition: "community"

webapp:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

server:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

postgresql:
  primary:
    persistence:
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

minio:
  persistence:
    size: 10Gi

# Enable ingress for dev
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: airbyte-dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: airbyte-dev-tls
      hosts:
        - airbyte-dev.example.com

# Disable metrics in dev (optional)
metrics:
  enabled: false

